### ISSUE TITLE
Retrieving the Api keys when using Hoobs.

### ISSUE THREAD

**Issue by cobch** [GlueHome/homebridge-plugin#6]
Could you please describe how to get the api keys in order to use the new homebridge plugin from Hoobs?

**Comment by kafouros** [comment]
Hi @cobch, thanks for reaching out.

Currently our plugin does not support automatic issuing of tokens in when installed in Hoobs. However, it is possible to manually retrieve and configure the Api-Key in Hoobs' plugin configuration page.

Currently, the only way of claiming such an Api-key for your account is to send a POST HTTP request to our service as specified [here](https://github.com/GlueHome/homebridge-plugin#requirements). If you are on a Windows system, where curl is not available out of the box, you could either use [Postman](https://www.postman.com/) or [curl for Windows](https://curl.se/windows/).

After setting the token up in Hoobs, your plugin should be up and running.

Have a great weekend.

**Comment by tarek86salmi** [comment]
Hi am not really good with this am using the ord api to get my glue lock on HomeKit but know if I remove the old api how should I do? 
how can I get the api key? 
am not really technical so please try to do it simple as the old Api

**Comment by kafouros** [comment]
Thanks for the patience @cobch and @tarek86salmi. We have just released a new version of the GlueHome homebridge plugin (v.0.2.0) which supports authentication using your Glue credentials. 

At initialisation, the plugin will issue an api-key under the hood, so that you don't need to mind about it. Of course, the api-key authentication option is still in place, in case stricter security is desired.

All you need to do after installing is to fill the following fields:
- Authentication Mode: "basic"
- Api-Key: <leave blank>
- Username: <your Glue account phone number or email (if it is verified)>
- Password: <your Glue account password>
 
Let us know if you run into any other issues. Have a great weekend.
