### ISSUE TITLE
Error 503: Hub is currently busy

### ISSUE THREAD

**Issue by mandrean** [GlueHome/homebridge-plugin#7]
Hi,

I set up HomeBridge with this new plugin, created an API key etc., but I can't get this working reliably with my hub and lock.

It locks & unlocks the door properly, but spams my HomeBridge console with a lot of `Error: Operation pending` and `503`s
```
data: {
      correlationId: '<SNIP>',
      code: 80000,
      title: 'Hub is currently busy. Try again in 60 seconds.',
      status: 503,
      detail: 'Hub is currently busy. Try again in 60 seconds.',
      instance: '/v1/locks/<SNIP>/operations'
    }
```

Also the Apple Home app reports the lock as non-working/non-responsive.

I switched back to the old community HomeBridge Glue plugin which works perfectly.

**Comment by kafouros** [comment]
Hi @mandrean, thanks a lot for your feedback.

I understand that these error logs may seem as noise. We will look into improving the information emitted in the terminal so that the plugin communicates the desired information in a more user friendly way.

However, the actual operation failure is a protection mechanism rather than an error. It does not originate from the plugin but from the core platform, which aims to indicate that the devices of the user are currently in use (i.e. "Hub is currently busy"). 

The most common cause is pending lock operation. Looking at our system's logs, I can see that an "unlock request" was sent at 01:53:14 UTC, which concluded at 01:53:33 UTC. Between those two times, there was an attempt to operate the lock 01:53:29 UTC which was intentionally responded with a 503 to indicate that the devices are currently busy and cannot accept another request.

This is a fundamental function of the system which aims to ensure the correct operation of the Glue Lock and it is applied regardless of the client from which the request originated. Thus, not using the Glue Homebridge plugin only hides this issue from your console.

Finally, I'd like to inform you that the API used by the old plugin will soon be obsoleted. In order to avoid any disruption to your service, unless the community Homebridge plugin migrates to our integrations API, I would recommend using the Glue Homebridge plugin, which is based on our new integrations API instead.

If you have any questions please ask. Have a great day!

**Comment by kafouros** [comment]
Hi @mandrean, I'd like to inform you that we have just released v.0.2.0 of our plugin which provides more graceful handling of the 503 busy error responses in the log stream of Homebridge. 

I will go ahead and close this ticket. Please let us know if there is anything that seem strange. Thanks.
